version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: veliora-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: veliora
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: veliora
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: veliora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
